/* ══════════════════════════════════════════════════════════════════════
   WAD & WEIDS — collectie en bestemmingen
   ──────────────────────────────────────────────────────────────────────
   De inhoud van het platform. In de mock-up staat dit in code; in de
   uiteindelijke website komt het uit de redactieomgeving, aangevuld met
   de velden die MyTourist aanlevert (zie types.ts). De pagina's kennen
   geen enkele woning bij naam — ze renderen wat hier staat.
   ══════════════════════════════════════════════════════════════════════ */
import type { Amenity, AmenityKey, Destination, Property } from "./types";

/* ── Voorzieningen ───────────────────────────────────────────────────
   filter: true = verschijnt als knop op de zoekpagina. */
export const AMENITIES: Amenity[] = [
  { key: "sauna", label: "Privésauna", group: "buiten", filter: true },
  { key: "jacuzzi", label: "Jacuzzi", group: "buiten", filter: true },
  { key: "buitendouche", label: "Buitendouche", group: "buiten" },
  { key: "terras", label: "Terras op het zuiden", group: "buiten" },
  { key: "tuin", label: "Eigen tuin", group: "buiten" },
  { key: "bbq", label: "Buitenkeuken", group: "buiten" },
  { key: "fietsen", label: "Fietsen inbegrepen", group: "buiten" },
  { key: "haard", label: "Houtkachel", group: "binnen" },
  { key: "keuken", label: "Volledig uitgeruste keuken", group: "binnen" },
  { key: "vaatwasser", label: "Vaatwasser", group: "binnen" },
  { key: "wasmachine", label: "Wasmachine en droger", group: "binnen" },
  { key: "vloerverwarming", label: "Vloerverwarming", group: "comfort" },
  { key: "wifi", label: "Snelle wifi", group: "comfort" },
  { key: "smart-tv", label: "Smart-tv", group: "comfort" },
  { key: "aan-het-water", label: "Aan het water", group: "locatie", filter: true },
  { key: "nabij-strand", label: "Op loopafstand van strand", group: "locatie", filter: true },
  { key: "in-natuur", label: "In natuurgebied", group: "locatie", filter: true },
  { key: "uitzicht", label: "Vrij uitzicht", group: "locatie" },
  { key: "laadpaal", label: "Laadpaal", group: "praktisch", filter: true },
  { key: "parkeren", label: "Eigen parkeerplaats", group: "praktisch" },
  { key: "huisdieren", label: "Huisdier welkom", group: "praktisch", filter: true },
  { key: "kindvriendelijk", label: "Kindvriendelijk", group: "praktisch", filter: true },
  { key: "rolstoel", label: "Gelijkvloers", group: "praktisch" },
];

export const AMENITY_LABEL: Record<AmenityKey, string> = Object.fromEntries(
  AMENITIES.map((a) => [a.key, a.label])
) as Record<AmenityKey, string>;

export const AMENITY_GROUPS: { key: Amenity["group"]; label: string }[] = [
  { key: "buiten", label: "Buiten" },
  { key: "binnen", label: "Binnen" },
  { key: "comfort", label: "Comfort" },
  { key: "locatie", label: "Ligging" },
  { key: "praktisch", label: "Praktisch" },
];

export const FILTER_AMENITIES = AMENITIES.filter((a) => a.filter);

/* ── Bestemmingen ───────────────────────────────────────────────────
   Uitbreiden is één record erbij; de tegelgrid vult zichzelf. */
export const DESTINATIONS: Destination[] = [
  {
    slug: "waddenkust",
    name: "Waddenkust",
    region: "Friesland & Groningen",
    intro: "Dijken, kwelders en een zee die twee keer per dag verdwijnt.",
    description:
      "Achter de dijk ligt het stilste stuk Nederland. Bij eb loop je het wad op, bij vloed hoor je alleen wind en vogels. Onze huizen staan hier op ruime kavels, meestal zonder buren in het zicht.",
    image: "/wad-weids/dest-waddenkust.svg",
    tile: "tall",
  },
  {
    slug: "kust-en-duinen",
    name: "Kust & Duinen",
    region: "Noord-Holland",
    intro: "Duinpannen, zeewind en een strand dat kilometers doorloopt.",
    description:
      "De duinenrij tussen Callantsoog en Den Helder is breed, ruig en verrassend leeg buiten het hoogseizoen. Vanaf het terras loop je in een kwartier over het duin naar zee.",
    image: "/wad-weids/dest-kust-duinen.svg",
    tile: "tall",
  },
  {
    slug: "friese-natuur",
    name: "Friese natuur",
    region: "Friesland",
    intro: "Terpen, weidevogels en een horizon zonder onderbreking.",
    description:
      "Het Friese kleigebied is weids op een manier die je moet zien om te geloven. Oude terpdorpen, smalle wegen en 's avonds een lucht die van de ene naar de andere kant kleurt.",
    image: "/wad-weids/dest-friese-natuur.svg",
  },
  {
    slug: "drenthe",
    name: "Drenthe",
    region: "Drenthe",
    intro: "Heide, houtwallen en het geluid van niets.",
    description:
      "Boswachterijen, stuifzand en heidevelden waar in augustus alles paars kleurt. Onze Drentse huizen staan aan de rand van het landschap, met de natuur als achtertuin.",
    image: "/wad-weids/dest-drenthe.svg",
    tile: "tall",
  },
  {
    slug: "noord-nederland",
    name: "Noord-Nederland",
    region: "Groningen",
    intro: "Ruimte, licht en dorpen waar de tijd anders loopt.",
    description:
      "Van het Lauwersmeer tot het Groningse wierdenland: donkere nachten, brede luchten en veel minder mensen dan je gewend bent.",
    image: "/wad-weids/dest-noord-nederland.svg",
  },
  {
    slug: "de-eilanden",
    name: "De eilanden",
    region: "Waddeneilanden",
    intro: "Overtocht, fiets, strand. Verder niets te doen — precies goed.",
    description:
      "Op Texel en Schiermonnikoog verandert het tempo zodra de boot afvaart. Auto blijft staan, fiets gaat mee, en de zee is nooit ver.",
    image: "/wad-weids/dest-eilanden.svg",
  },
];

/* ── De collectie ────────────────────────────────────────────────────
   Acht woningen in de mock-up. Vijftig woningen gebruikt exact dezelfde
   velden en dezelfde componenten. */
export const PROPERTIES: Property[] = [
  {
    id: "MT-1041",
    slug: "wadzicht",
    name: "Wadzicht",
    tagline: "Achter de zeedijk, met de wadvogels als buren.",
    place: "Paesens-Moddergat",
    destination: "waddenkust",
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    size: 128,
    priceFrom: 345,
    cleaningFee: 145,
    touristTaxPerPersonPerNight: 2.1,
    minNights: 2,
    badge: "Aan het wad",
    amenities: ["sauna", "haard", "terras", "tuin", "buitendouche", "keuken", "vaatwasser", "wasmachine", "vloerverwarming", "wifi", "smart-tv", "laadpaal", "parkeren", "fietsen", "aan-het-water", "in-natuur", "uitzicht", "kindvriendelijk"],
    highlights: [
      "Vijftig meter van de zeedijk, met zicht over de kwelder",
      "Privésauna met uitzicht op het wad",
      "Vier e-bikes en twee wandelstokken staan klaar",
      "Wadlooptochten vertrekken op loopafstand",
    ],
    description: [
      "Wadzicht staat waar Nederland ophoudt. Achter het huis loopt de zeedijk, daarachter de kwelder, en daarachter niets dan wad tot aan de eilanden. Bij eb hoor je alleen wulpen; bij storm zie je het water tegen de dijk slaan terwijl je binnen bij de kachel zit.",
      "Het huis is in 2023 volledig verbouwd door een architect uit Dokkum: eikenhouten vloeren, kalkstuc, en een pui van vijf meter breed die de kwelder naar binnen haalt. De keuken is compleet, inclusief goede messen en een espressomachine die het doet.",
      "Drie slaapkamers, twee badkamers, en een zolderkamer die net zo goed werkt als werkplek. De sauna staat in het bijgebouw, met een raam dat precies op de dijk uitkijkt.",
    ],
    images: [
      { src: "/wad-weids/wad-1.svg", alt: "Zicht over het wad bij opkomend tij" },
      { src: "/wad-weids/wad-2.svg", alt: "Het huis achter de zeedijk in de ochtend" },
      { src: "/wad-weids/wad-3.svg", alt: "Palen in het wad bij laag water" },
      { src: "/wad-weids/wad-4.svg", alt: "Avondlicht boven de kwelder" },
      { src: "/wad-weids/wad-5.svg", alt: "Het terras met uitzicht op de dijk" },
    ],
    extras: [
      { key: "sauna-avond", label: "Sauna voorverwarmd bij aankomst", description: "Klaar op het tijdstip dat je doorgeeft.", price: 35, unit: "once" },
      { key: "ontbijtmand", label: "Ontbijtmand van de bakker in Ternaard", description: "Vers brood, eieren en zuivel uit de streek.", price: 24, unit: "person" },
      { key: "linnen-extra", label: "Extra bedlinnen en handdoeken", description: "Naast de standaard set per gast.", price: 18, unit: "once" },
    ],
    coordinates: { lat: 53.4022, lon: 6.0286 },
  },
  {
    id: "MT-1042",
    slug: "duin-en-dauw",
    name: "Duin & Dauw",
    tagline: "Een duinhuis met de zee achter de eerste rij.",
    place: "Callantsoog",
    destination: "kust-en-duinen",
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: 92,
    priceFrom: 295,
    cleaningFee: 120,
    touristTaxPerPersonPerNight: 1.85,
    minNights: 2,
    amenities: ["terras", "tuin", "buitendouche", "keuken", "vaatwasser", "wasmachine", "wifi", "smart-tv", "vloerverwarming", "parkeren", "fietsen", "nabij-strand", "in-natuur", "huisdieren", "kindvriendelijk", "rolstoel"],
    highlights: [
      "Twaalf minuten lopen door het duin naar zee",
      "Volledig gelijkvloers, ook met kinderwagen prettig",
      "Buitendouche voor na het strand",
      "Hond is welkom, duinpad begint bij het hek",
    ],
    description: [
      "Duin & Dauw ligt aan de rand van het dorp, met het duin direct achter de tuin. Vanaf het terras zie je de duinrand oplopen; over het pad ben je in een kwartier bij de vloedlijn.",
      "Binnen is het licht en rustig: witte wanden, essenhout, linnen gordijnen. Twee slaapkamers, één ruime badkamer met inloopdouche, en een woonkeuken waar vier mensen prettig samen koken.",
      "Het huis is gelijkvloers en drempelloos, met een brede buitendouche naast de achterdeur — precies wat je wilt na een dag zand.",
    ],
    images: [
      { src: "/wad-weids/duin-2.svg", alt: "Het huis aan de duinrand in het ochtendlicht" },
      { src: "/wad-weids/duin-1.svg", alt: "Duinpan bij dauw" },
      { src: "/wad-weids/duin-3.svg", alt: "Duinpad richting zee" },
      { src: "/wad-weids/duin-4.svg", alt: "Avond boven de duinen" },
      { src: "/wad-weids/duin-5.svg", alt: "Helmgras op de duinrand" },
    ],
    extras: [
      { key: "strandpakket", label: "Strandpakket", description: "Twee strandstoelen, parasol en windscherm.", price: 30, unit: "once" },
      { key: "huisdier", label: "Hond", description: "Inclusief mand, kom en handdoek.", price: 12, unit: "night" },
    ],
    coordinates: { lat: 52.8407, lon: 4.6963 },
  },
  {
    id: "MT-1043",
    slug: "de-weidsheid",
    name: "De Weidsheid",
    tagline: "Alleen op de heide, met een jacuzzi onder de sterren.",
    place: "Zeijen",
    destination: "drenthe",
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: 78,
    priceFrom: 265,
    cleaningFee: 95,
    touristTaxPerPersonPerNight: 1.7,
    minNights: 2,
    badge: "Meest geboekt",
    amenities: ["jacuzzi", "haard", "terras", "tuin", "bbq", "keuken", "vaatwasser", "wasmachine", "vloerverwarming", "wifi", "smart-tv", "laadpaal", "parkeren", "fietsen", "in-natuur", "uitzicht", "huisdieren", "rolstoel"],
    highlights: [
      "Vrijstaand op eigen kavel aan de rand van de heide",
      "Privéjacuzzi op het terras, het hele jaar warm",
      "Geen receptie, geen slagboom, geen buren in het zicht",
      "Donkere nachten — je ziet hier de Melkweg",
    ],
    description: [
      "De Weidsheid staat alleen aan de rand van het heideveld bij Zeijen. Geen park, geen buren binnen gehoorsafstand: je rijdt het zandpad op, parkeert naast het huis en dat is het.",
      "De lodge is compact en compleet. Vloerverwarming, een houtkachel voor de avonden, een keuken met alles erin en een pui die helemaal open kan. Buiten: een verwarmde jacuzzi, een lange houten tafel en een vuurschaal.",
      "In augustus kleurt de heide paars tot aan de horizon. In november is het hier mistig en stil, en zit je binnen met de kachel aan terwijl de schapen langskomen.",
    ],
    images: [
      { src: "/lodge-heide.jpg", alt: "De lodge in het avondlicht met de jacuzzi op het terras" },
      { src: "/heide1.jpg", alt: "Schaapskudde op de Drentse heide" },
      { src: "/lodge-eik.jpg", alt: "De lodge tussen de eiken" },
      { src: "/heide2.jpg", alt: "Heidelandschap bij zonsopkomst" },
      { src: "/heide3.jpg", alt: "Wandelpad door het heideveld" },
    ],
    extras: [
      { key: "jacuzzi-warm", label: "Jacuzzi op temperatuur bij aankomst", description: "38 graden zodra je binnenkomt.", price: 25, unit: "once" },
      { key: "houtpakket", label: "Haardhout en aanmaakhout", description: "Genoeg voor drie avonden.", price: 28, unit: "once" },
      { key: "borrelplank", label: "Borrelplank uit de streek", description: "Drentse kazen, worst en brood.", price: 32, unit: "once" },
    ],
    coordinates: { lat: 53.0567, lon: 6.5175 },
  },
  {
    id: "MT-1044",
    slug: "zeezicht",
    name: "Zeezicht",
    tagline: "Bovenaan de dijk op Texel, met uitzicht tot aan Vlieland.",
    place: "Oosterend, Texel",
    destination: "de-eilanden",
    guests: 5,
    bedrooms: 3,
    bathrooms: 2,
    size: 116,
    priceFrom: 365,
    cleaningFee: 135,
    touristTaxPerPersonPerNight: 2.65,
    minNights: 3,
    amenities: ["sauna", "haard", "terras", "keuken", "vaatwasser", "wasmachine", "wifi", "smart-tv", "vloerverwarming", "laadpaal", "parkeren", "fietsen", "aan-het-water", "uitzicht", "in-natuur", "kindvriendelijk"],
    highlights: [
      "Vrij zicht over de Waddenzee vanaf de eerste verdieping",
      "Vijf minuten fietsen naar de haven van Oudeschild",
      "Sauna met dakraam, ideaal na een dag wind",
      "Zonsondergang op het balkon, elke avond opnieuw",
    ],
    description: [
      "Zeezicht staat aan de rand van Oosterend, met de dijk aan de achterkant en het wad daarachter. Vanaf de bovenverdieping kijk je over het water tot aan de kop van Vlieland.",
      "Het huis is opgezet als een eilandhuis hoort: veel hout, dikke muren, een kachel die de hele benedenverdieping warm houdt. Drie slaapkamers, twee badkamers, en een keuken die tegen een week koken kan.",
      "Fietsen staan in de schuur. Naar het strand bij paal 17 is het twintig minuten fietsen door de polder — een rit die je elke dag opnieuw wilt maken.",
    ],
    images: [
      { src: "/wad-weids/zee-4.svg", alt: "Zonsondergang boven de Waddenzee" },
      { src: "/wad-weids/zee-2.svg", alt: "Het huis in het avondlicht" },
      { src: "/wad-weids/zee-1.svg", alt: "De dijk bij Oosterend" },
      { src: "/wad-weids/zee-3.svg", alt: "Uitzicht over het water" },
      { src: "/wad-weids/zee-5.svg", alt: "Avond op het balkon" },
    ],
    extras: [
      { key: "boot-transfer", label: "Reservering bootovertocht", description: "Wij regelen de tickets voor auto en passagiers.", price: 0, unit: "once" },
      { key: "vismand", label: "Vismand uit Oudeschild", description: "Verse vis van de afslag, geleverd op de aankomstdag.", price: 45, unit: "once" },
    ],
    coordinates: { lat: 53.0895, lon: 4.8578 },
  },
  {
    id: "MT-1045",
    slug: "het-waddenhuis",
    name: "Het Waddenhuis",
    tagline: "Een oude pastorie voor tien, aan de rand van Holwerd.",
    place: "Holwerd",
    destination: "waddenkust",
    guests: 10,
    bedrooms: 5,
    bathrooms: 3,
    size: 240,
    priceFrom: 495,
    cleaningFee: 210,
    touristTaxPerPersonPerNight: 2.1,
    minNights: 3,
    badge: "Groepen tot 10",
    amenities: ["sauna", "haard", "terras", "tuin", "bbq", "keuken", "vaatwasser", "wasmachine", "wifi", "smart-tv", "vloerverwarming", "laadpaal", "parkeren", "fietsen", "in-natuur", "uitzicht", "huisdieren", "kindvriendelijk"],
    highlights: [
      "Vijf slaapkamers, drie badkamers — iedereen slaapt goed",
      "Eettafel voor twaalf, keuken met twee ovens",
      "Ommuurde tuin met vuurplaats en buitenkeuken",
      "Boot naar Ameland vertrekt op tien minuten rijden",
    ],
    description: [
      "Het Waddenhuis is de voormalige pastorie van Holwerd: hoge plafonds, diepe vensterbanken en een ommuurde tuin waar de wind niet bij kan. Het huis is met zorg gerestaureerd en ingericht voor groepen die samen willen zijn zonder over elkaar heen te lopen.",
      "Beneden een woonkamer met open haard, een tweede zitkamer en een keuken die op een gezelschap van tien is gebouwd. Boven vijf slaapkamers, allemaal met eigen karakter en goede bedden.",
      "Ideaal voor familieweekenden, vriendengroepen en werksessies die eigenlijk vakantie zijn. De sauna zit in het koetshuis achter in de tuin.",
    ],
    images: [
      { src: "/wad-weids/blauw-1.svg", alt: "Het wad bij het blauwe uur" },
      { src: "/wad-weids/blauw-2.svg", alt: "Het huis in de avond" },
      { src: "/wad-weids/blauw-4.svg", alt: "Schemer boven de kwelder" },
      { src: "/wad-weids/blauw-3.svg", alt: "Palen in het water" },
      { src: "/wad-weids/blauw-5.svg", alt: "Zicht richting de pier van Holwerd" },
    ],
    extras: [
      { key: "kok", label: "Kok aan huis", description: "Driegangendiner uit de streek, klaargemaakt in het huis.", price: 65, unit: "person" },
      { key: "kinderbed", label: "Kinderbed en kinderstoel", description: "Compleet met linnen.", price: 20, unit: "once" },
      { key: "houtpakket", label: "Haardhout", description: "Voor de open haard en de vuurplaats.", price: 35, unit: "once" },
    ],
    coordinates: { lat: 53.3714, lon: 5.8874 },
  },
  {
    id: "MT-1046",
    slug: "duinrand",
    name: "Duinrand",
    tagline: "Schiermonnikoog, waar de auto aan de wal blijft.",
    place: "Schiermonnikoog",
    destination: "de-eilanden",
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    size: 84,
    priceFrom: 325,
    cleaningFee: 125,
    touristTaxPerPersonPerNight: 2.4,
    minNights: 3,
    amenities: ["haard", "terras", "tuin", "buitendouche", "keuken", "vaatwasser", "wifi", "vloerverwarming", "fietsen", "nabij-strand", "in-natuur", "uitzicht", "kindvriendelijk"],
    highlights: [
      "Aan de rand van het dorp, duinpad achter de tuin",
      "Vier fietsen staan klaar bij aankomst",
      "Het breedste strand van Europa op tien minuten",
      "Nationaal park begint waar de tuin ophoudt",
    ],
    description: [
      "Duinrand is een klein, warm huis aan de westkant van het dorp. Achter de tuin begint het duin, en daarachter ligt het strand waar je op een doordeweekse dag in oktober niemand tegenkomt.",
      "Binnen: een houtkachel, twee slaapkamers met goede bedden, en een keuken die genoeg is voor vier. Buiten: een beschut terras en een buitendouche tegen de schuur.",
      "De auto laat je op de wal. Fietsen staan klaar, en verder heb je op Schiermonnikoog niets nodig.",
    ],
    images: [
      { src: "/wad-weids/strand-2.svg", alt: "Het huis aan de duinrand" },
      { src: "/wad-weids/strand-1.svg", alt: "Breed strand bij laag water" },
      { src: "/wad-weids/strand-3.svg", alt: "Duinpad naar zee" },
      { src: "/wad-weids/strand-4.svg", alt: "Avondlicht op het strand" },
      { src: "/wad-weids/strand-5.svg", alt: "Helmgras in de wind" },
    ],
    extras: [
      { key: "bagage", label: "Bagageservice vanaf de boot", description: "Je koffers staan er als je aankomt.", price: 20, unit: "once" },
      { key: "ontbijtmand", label: "Ontbijtmand", description: "Van de dorpsbakker, elke ochtend vers.", price: 22, unit: "person" },
    ],
    coordinates: { lat: 53.4797, lon: 6.1592 },
  },
  {
    id: "MT-1047",
    slug: "de-kwelder",
    name: "De Kwelder",
    tagline: "Aan het Lauwersmeer, met een steiger voor de deur.",
    place: "Lauwersoog",
    destination: "noord-nederland",
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    size: 134,
    priceFrom: 335,
    cleaningFee: 140,
    touristTaxPerPersonPerNight: 1.95,
    minNights: 2,
    badge: "Nieuw",
    amenities: ["sauna", "terras", "tuin", "keuken", "vaatwasser", "wasmachine", "wifi", "smart-tv", "vloerverwarming", "laadpaal", "parkeren", "fietsen", "aan-het-water", "in-natuur", "uitzicht", "kindvriendelijk", "huisdieren"],
    highlights: [
      "Eigen steiger met roeiboot en kano",
      "Donkertegebied: 's nachts zie je alles",
      "Sauna met uitzicht over het riet",
      "Zeehondenexcursies vertrekken uit de haven",
    ],
    description: [
      "De Kwelder ligt aan een zijarm van het Lauwersmeer, met riet aan drie kanten en een steiger die de tuin in het water laat lopen. Nationaal Park Lauwersmeer is een van de donkerste plekken van Nederland — op een heldere avond is de sterrenhemel hier het uitzicht.",
      "Het huis is nieuw en met natuurlijke materialen gebouwd: houten gevel, leem, drievoudig glas. Drie slaapkamers, twee badkamers en een woonkamer die aan twee zijden open is.",
      "Roeiboot en kano liggen aan de steiger. Fietsen staan in de berging, en de haven van Lauwersoog is tien minuten rijden.",
    ],
    images: [
      { src: "/wad-weids/kwelder-5.svg", alt: "Het huis aan het water in de namiddag" },
      { src: "/wad-weids/kwelder-1.svg", alt: "Kwelder met laagstaande zon" },
      { src: "/wad-weids/kwelder-2.svg", alt: "Steiger aan het riet" },
      { src: "/wad-weids/kwelder-3.svg", alt: "Mist boven het meer" },
      { src: "/wad-weids/kwelder-4.svg", alt: "Avond boven het Lauwersmeer" },
    ],
    extras: [
      { key: "sup", label: "Twee supboards", description: "Inclusief peddels en vesten.", price: 30, unit: "once" },
      { key: "sauna-avond", label: "Sauna voorverwarmd", description: "Op het tijdstip dat je doorgeeft.", price: 30, unit: "once" },
    ],
    coordinates: { lat: 53.3958, lon: 6.2144 },
  },
  {
    id: "MT-1048",
    slug: "terpzicht",
    name: "Terpzicht",
    tagline: "Een kop-hals-rompboerderij op de hoogste terp van Friesland.",
    place: "Hegebeintum",
    destination: "friese-natuur",
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    size: 152,
    priceFrom: 310,
    cleaningFee: 130,
    touristTaxPerPersonPerNight: 1.8,
    minNights: 2,
    amenities: ["haard", "terras", "tuin", "bbq", "keuken", "vaatwasser", "wasmachine", "wifi", "vloerverwarming", "parkeren", "fietsen", "in-natuur", "uitzicht", "huisdieren", "kindvriendelijk"],
    highlights: [
      "Uitzicht over het wierdenlandschap, tot twintig kilometer ver",
      "Ochtendmist over de weilanden, bijna het hele jaar",
      "Grote keuken met lange tafel voor zes",
      "Dokkum en de Waddenkust op een halfuur rijden",
    ],
    description: [
      "Terpzicht is het voorhuis van een oude Friese boerderij op de hoogste terp van het land. Vanaf de eettafel kijk je over de weilanden; op mistige ochtenden steken alleen de kerktorens boven het wit uit.",
      "Het voorhuis is verbouwd met respect voor wat er stond: bedstedes werden kasten, de deel werd een woonkeuken, de vensterbanken bleven diep. Drie slaapkamers, twee badkamers, en een houtkachel die het hele huis warm krijgt.",
      "Buiten een beschutte tuin met een lange tafel en een vuurplaats. Fietsroutes beginnen bij het hek, de Waddenkust ligt een half uur verderop.",
    ],
    images: [
      { src: "/wad-weids/mist-3.svg", alt: "Ochtendmist over het Friese land" },
      { src: "/wad-weids/mist-2.svg", alt: "De boerderij in het landschap" },
      { src: "/wad-weids/mist-1.svg", alt: "Weiland bij zonsopkomst" },
      { src: "/wad-weids/mist-4.svg", alt: "Avond boven de terp" },
      { src: "/wad-weids/mist-5.svg", alt: "Zicht over de weilanden" },
    ],
    extras: [
      { key: "ontbijtmand", label: "Ontbijtmand", description: "Brood, zuivel en eieren van de buren.", price: 21, unit: "person" },
      { key: "houtpakket", label: "Haardhout", description: "Voor kachel en vuurplaats.", price: 26, unit: "once" },
    ],
    coordinates: { lat: 53.3383, lon: 5.8442 },
  },
];
